server.port: 8081
#dev mode disable zipkin
spring.cloud.kubernetes.zipkin.discovery.enabled: false
#开发环境关闭kubernetes discovery
spring.cloud.kubernetes.discovery.enabled: false


ipclient.serviceUrl:  http://172.16.5.23:8080/ip