spring.application.name: ipclient
spring.main.sources: cn.vpclub
spring.sleuth.sampler.percentage: 1.0
logging.config: classpath:logback.xml

welcome:  Hello World!
ipclient.serviceUrl: http://ipservicedemo/ip